libcore_private.stubs cannot be built with JDK9
The package sun.misc in the stubs library is causing module name
conflict when building with JDK9.

error: package exists in another module: jdk.unsupported

Fixing the error by setting java_version to 1.7 so that modules are not
used when building the stubs lib.

Bug: 74211600
Test: EXPERIMENTAL_USE_OPENJDK9=true m -j libcore_private.stubs

Change-Id: Ifa709bef2dc8e2b11048ef96fc7517d8c25e8a7f