Add -Wno-deprecated-declarations to external/protobuf
This fixes building with Mac OS SDK >= 13.

Without this flag, the following error occurs:

    error: 'sprintf' is deprecated: This function is provided for compatibility
reasons only.  Due to security concerns inherent in the design of sprintf(3),
it is highly recommended that you use snprintf(3) instead.
[-Werror,-Wdeprecated-declarations]

Change-Id: Ic4c54c01def4ff03b83f57dacf01a45d57986a7b