Build libprotobuf-java-lite only using core Java SDK APIs
libprotobuf-java-lite is now built against core Java APIs which excludes
Android-only APIs (classes under android.* packages) and private APIs.
"core_current" is a pseudo SDK which is a core Java subset of Android
SDK.

However, this lib has been using sun.misc.Unsafe which is a hidden API
and dependency to the class doesn't seem to be able to be cut easily in
the near future. In order to make it possible to build the lib with the
SDK only, a stubs library called libcore_private.stubs is defined to
provide build-time only information on the hidden APIs exclusively to
protobuf.

At runtime, the Unsafe class is provide by the OS and protobuf is linked
to the class loaded there.

Bug: 73204840
Test: m -j libprotobuf-java-lite is successful and does not show any
link-type check warning

Merged-In: I2fce2662cc65d4e57fc75bbf30ebf9f7d47c6775
(cherry picked from commit dc08924dc7262e5c06c1108f67f66e82598af806)

libcore_private.stubs cannot be built with JDK9

The package sun.misc in the stubs library is causing module name
conflict when building with JDK9.

error: package exists in another module: jdk.unsupported

Fixing the error by setting java_version to 1.7 so that modules are not
used when building the stubs lib.

Bug: 74211600
Test: EXPERIMENTAL_USE_OPENJDK9=true m -j libcore_private.stubs

Merged-In: Ifa709bef2dc8e2b11048ef96fc7517d8c25e8a7f
(cherry picked from commit 0e4379e7504849d7a2755b9a0264cd7901accc88)

libcore_private.stubs is uninstallable

Make sure that libcore_private.stubs isn't installed to the device as a
standalone jar library. The lib is meant to provide build-time only
symbol information to protobuf and thus is not runnable.

Bug: 73204840
Test: m -j libcore_private.stubs does not create
libcore_private.stubs.jar in /system/framework

Merged-In: I7c661211161937dba5ee71fdc4bb8b9f101c5a59
(cherry picked from commit 6297aad4d72232863366d62ae8799ce9cf492a43)

Don't force libcore_private.stubs to be built with java 1.7

We no longer need to build libcore_private.stubs with java 1.7, because
the library is only built for target and not for host, where it
conflicts with the module jdk.unsupported.

Bug: 74211600
Test: m -j libprotobuf-java-lite is successful. both host and target
variant of the lib is generated.
Test: EXPERIMENTAL_USE_OPENJDK9=true m -j libprotobuf-java-lite is also
successful.

Merged-In: I61a49d537ee6abad29e5661944ffc612a94465b8
(cherry picked from commit ed6d68ed9747c96d54d6773af40060e780443b1a)

Change-Id: I256652071b8a11cfbebcf6a4906546e6434f7372